exclude some none windows compiler flags, make zlib include/linker files available
- cl : Command line error D8021 : invalid numeric argument '/Wno-missing-braces'
- ..\src\VehicleSetup\FirmwareUpgradeController.cc(29): fatal error C1083: Cannot open include file: 'zlib.h': No such file or directory